"""initial

Revision ID: 3547bd46bbf7
Revises: 
Create Date: 2026-06-11 15:36:41.686364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3547bd46bbf7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('job_application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pipeline_data', sa.JSON(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_task_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['stage_task_id'], ['stage_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('note_fts_config')
    op.drop_table('note_fts_docsize')
    op.drop_table('note_fts_data')
    op.drop_table('note_fts')
    op.drop_table('note_fts_idx')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('note_fts',
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('content', sa.NullType(), nullable=True)
    )
    op.create_table('note_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.drop_table('task_event')
    op.drop_table('pipeline_item')
    op.drop_table('job_application')
    op.drop_table('career_config')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
